server:
  port: 8086
hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.loser.tradeservice.controller
feign:
  okhttp:
    enabled: true  # 表示开启连接池功能
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123