server:
  port: 8087
feign:
  okhttp:
    enabled: true  # 表示开启连接池功能,这是每一个微服务中的配置信息
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123