server:
  port: 8081
hm:
  db:
    database: hm-item
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.loser.itemservice.controller

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123